"""Command-line interface for githublab-sync."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from githublab_sync import __version__
from githublab_sync.config import Config, ConfigError, load_config
from githublab_sync.logging_utils import configure_logging
from githublab_sync.providers import build_provider
from githublab_sync.providers.base import ProviderError
from githublab_sync.sync import SyncSummary, sync_all

DEFAULT_CONFIG = "githublab-sync.yaml"

_CONFIG_TEMPLATE = """\
# githublab-sync configuration
# Tokens are read from the environment via ${VAR} so secrets stay out of git.
github:
  owner: your-github-user-or-org
  token: ${GITHUB_TOKEN}
  # host: github.com
  # api_url: https://api.github.com

gitlab:
  owner: your-gitlab-group-or-user
  token: ${GITLAB_TOKEN}
  # host: gitlab.com
  # api_url: https://gitlab.com/api/v4

sync:
  direction: bidirectional       # bidirectional | github-to-gitlab | gitlab-to-github
  create_missing: true           # create the repo on a provider if it is absent
  sync_branches: true
  sync_tags: true
  sync_pull_requests: true
  strip_ai_attribution: true     # remove AI co-author/"generated by" markers from PRs/MRs
  default_visibility: private     # private | public | internal (for newly created mirrors)
  # cache_dir: ~/.cache/githublab-sync

repositories:
  - my-first-repo
  - name: service-with-different-names
    github_name: service-api
    gitlab_name: service-api-mirror
"""


def _add_common(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "-c",
        "--config",
        default=DEFAULT_CONFIG,
        help=f"Path to the configuration file (default: {DEFAULT_CONFIG})",
    )
    parser.add_argument("-v", "--verbose", action="store_true", help="Verbose logging")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="githublab-sync",
        description="Bidirectional mirror & pull-request sync between GitHub and GitLab.",
    )
    parser.add_argument("--version", action="version", version=f"githublab-sync {__version__}")
    sub = parser.add_subparsers(dest="command", required=True)

    p_init = sub.add_parser("init", help="Write a starter configuration file")
    p_init.add_argument(
        "-c", "--config", default=DEFAULT_CONFIG, help="Where to write the config"
    )
    p_init.add_argument(
        "--force", action="store_true", help="Overwrite an existing config file"
    )

    p_sync = sub.add_parser("sync", help="Run a sync across all configured repositories")
    _add_common(p_sync)
    p_sync.add_argument(
        "--dry-run", action="store_true", help="Show what would happen without making changes"
    )
    p_sync.add_argument(
        "--repo",
        action="append",
        default=None,
        metavar="NAME",
        help="Limit the run to one repository (repeatable)",
    )
    p_sync.add_argument(
        "--direction",
        choices=["bidirectional", "github-to-gitlab", "gitlab-to-github"],
        help="Override the configured sync direction",
    )

    p_doctor = sub.add_parser("doctor", help="Check configuration, tokens and connectivity")
    _add_common(p_doctor)

    return parser


def _cmd_init(args: argparse.Namespace) -> int:
    target = Path(args.config)
    if target.exists() and not args.force:
        print(f"Refusing to overwrite existing {target} (use --force)", file=sys.stderr)
        return 1
    target.write_text(_CONFIG_TEMPLATE, encoding="utf-8")
    print(f"Wrote starter config to {target}")
    print("Next: set GITHUB_TOKEN and GITLAB_TOKEN, edit the file, then run "
          "'githublab-sync doctor'.")
    return 0


def _load(args: argparse.Namespace) -> Config:
    config = load_config(args.config)
    if getattr(args, "direction", None):
        config.sync.direction = args.direction
    if getattr(args, "repo", None):
        wanted = set(args.repo)
        config.repositories = [r for r in config.repositories if r.name in wanted]
        if not config.repositories:
            raise ConfigError(f"No configured repositories match {sorted(wanted)}")
    return config


def _cmd_doctor(args: argparse.Namespace) -> int:
    log = configure_logging(args.verbose)
    try:
        config = _load(args)
    except ConfigError as exc:
        log.error("config: %s", exc)
        return 2

    ok = True
    for provider_config in (config.github, config.gitlab):
        label = provider_config.kind
        if not provider_config.has_token:
            log.error("%s: no token set", label)
            ok = False
            continue
        try:
            provider = build_provider(provider_config)
            who = provider.whoami()
            log.info("%s: authenticated as '%s' (owner: %s)", label, who, provider_config.owner)
        except ProviderError as exc:
            log.error("%s: authentication failed: %s", label, exc)
            ok = False

    log.info(
        "direction=%s create_missing=%s repos=%d",
        config.sync.direction,
        config.sync.create_missing,
        len(config.repositories),
    )
    return 0 if ok else 1


def _print_summary(summary: SyncSummary, log) -> None:
    created = sum(len(r.created_on) for r in summary.results)
    branches = sum(len(r.git_report.branch_actions) for r in summary.results)
    tags = sum(len(r.git_report.tag_actions) for r in summary.results)
    prs = sum(1 for r in summary.results for a in r.pr_actions if a.created)
    log.info(
        "done: %d repos, %d mirrors created, %d branch updates, %d tag updates, "
        "%d PR/MRs opened, %d conflicts, %d errors",
        len(summary.results),
        created,
        branches,
        tags,
        prs,
        summary.conflict_count,
        summary.error_count,
    )


def _cmd_sync(args: argparse.Namespace) -> int:
    log = configure_logging(args.verbose)
    try:
        config = _load(args)
    except ConfigError as exc:
        log.error("config: %s", exc)
        return 2

    if args.dry_run:
        log.info("DRY RUN — no changes will be made")

    summary = sync_all(config, dry_run=args.dry_run)
    _print_summary(summary, log)

    if summary.error_count:
        return 1
    if summary.conflict_count:
        return 3  # distinct code: ran cleanly but human review is needed
    return 0


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if args.command == "init":
        return _cmd_init(args)
    if args.command == "doctor":
        return _cmd_doctor(args)
    if args.command == "sync":
        return _cmd_sync(args)
    return 2  # pragma: no cover - argparse enforces a valid command


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
