"""Utilities for scrubbing AI-authorship attribution from text.

The sync tool never adds AI attribution to anything it writes, and when this
option is enabled it also strips common AI co-author / "generated by" trailers
from pull-request and merge-request titles and descriptions before mirroring
them to the other provider.

Git *commit history* is mirrored verbatim by default (rewriting history is
destructive); see ``git_ops.scrub_commit_messages`` for an opt-in rewrite.
"""

from __future__ import annotations

import re

# Lines that advertise AI authorship. Matched case-insensitively, whole line.
_AI_LINE_PATTERNS = [
    re.compile(r"^\s*co-authored-by:\s*claude\b.*$", re.IGNORECASE),
    re.compile(r"^\s*co-authored-by:.*<noreply@anthropic\.com>\s*$", re.IGNORECASE),
    re.compile(r"^\s*co-authored-by:.*\bcopilot\b.*$", re.IGNORECASE),
    re.compile(r"^\s*generated with \[?claude code\]?.*$", re.IGNORECASE),
    re.compile(r"^\s*🤖\s*generated with.*$", re.IGNORECASE),
    re.compile(r"^\s*assisted-by:\s*(claude|chatgpt|gpt-?\d|copilot).*$", re.IGNORECASE),
    re.compile(r"^\s*generated[- ]by:\s*(claude|chatgpt|gpt-?\d|copilot).*$", re.IGNORECASE),
]

# Inline fragments to remove even when they share a line with other content.
_AI_INLINE_PATTERNS = [
    re.compile(r"\s*🤖\s*generated with \[?claude code\]?\([^)]*\)", re.IGNORECASE),
    re.compile(r"\s*generated with \[?claude code\]?\([^)]*\)", re.IGNORECASE),
]


def strip_ai_attribution(text: str) -> str:
    """Return ``text`` with AI authorship trailers and markers removed.

    Whole lines that are nothing but an AI trailer are dropped; inline AI
    markers are excised. Trailing blank lines left behind are trimmed.
    """
    if not text:
        return text

    cleaned_lines: list[str] = []
    for line in text.splitlines():
        if any(p.match(line) for p in _AI_LINE_PATTERNS):
            continue
        for inline in _AI_INLINE_PATTERNS:
            line = inline.sub("", line)
        cleaned_lines.append(line)

    # Collapse trailing whitespace-only lines.
    while cleaned_lines and not cleaned_lines[-1].strip():
        cleaned_lines.pop()

    result = "\n".join(cleaned_lines)
    # Preserve a trailing newline if the original had one and content remains.
    if text.endswith("\n") and result:
        result += "\n"
    return result


def contains_ai_attribution(text: str) -> bool:
    """True if ``text`` carries any recognised AI authorship marker."""
    if not text:
        return False
    for line in text.splitlines():
        if any(p.match(line) for p in _AI_LINE_PATTERNS):
            return True
    return any(p.search(text) for p in _AI_INLINE_PATTERNS)
